name: My Workflow
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository information
        run: |
          echo "Repository name: ${{ github.event.repository.name }}"
          echo "Repository owner: ${{ github.event.repository.owner.login }}"
